In [ ]:
!pip install pycaret==2.0
!pip install shap

Collecting pycaret==2.0
  Downloading https://files.pythonhosted.org/packages/91/ae/000d825af8f7d9ff86808600f220e7ad57a873987fd6119c87dc4c5b1d91/pycaret-2.0-py3-none-any.whl (255kB)
     |████████████████████████████████| 256kB 8.6MB/s
Requirement already satisfied: joblib in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.16.0)
Collecting lightgbm>=2.3.1
  Downloading https://files.pythonhosted.org/packages/0b/9d/ddcb2f43aca194987f1a99e27edf41cf9bc39ea750c3371c2a62698c509a/lightgbm-2.3.1-py2.py3-none-manylinux1_x86_64.whl (1.2MB)
     |████████████████████████████████| 1.2MB 18.8MB/s
Collecting DateTime>=4.3
  Downloading https://files.pythonhosted.org/packages/73/22/a5297f3a1f92468cc737f8ce7ba6e5f245fcfafeae810ba37bd1039ea01c/DateTime-4.3-py2.py3-none-any.whl (60kB)
     |████████████████████████████████| 61kB 6.5MB/s
Collecting scikit-learn>=0.23
  Downloading https://files.pythonhosted.org/packages/5c/a1/273def87037a7fb010512bbc5901c31cfddfca8080bc63b42b26e3cc55b3/scikit_learn-0.23.2-cp36-cp36m-manylinux1_x86_64.whl (6.8MB)
     |████████████████████████████████| 6.8MB 51.3MB/s
Requirement already satisfied: wordcloud in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (1.5.0)
Requirement already satisfied: plotly>=4.4.1 in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (4.4.1)
Requirement already satisfied: xgboost>=0.90 in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.90)
Requirement already satisfied: gensim in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (3.6.0)
Requirement already satisfied: textblob in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.15.3)
Collecting yellowbrick>=1.0.1
  Downloading https://files.pythonhosted.org/packages/13/95/a14e4fdfb8b1c8753bbe74a626e910a98219ef9c87c6763585bbd30d84cf/yellowbrick-1.1-py3-none-any.whl (263kB)
     |████████████████████████████████| 266kB 54.4MB/s
Collecting pyod
  Downloading https://files.pythonhosted.org/packages/77/4e/5767edaccbfc227914ca774cb6ca9b628a08cbb59b9b4839296953a63d34/pyod-0.8.1.tar.gz (93kB)
     |████████████████████████████████| 102kB 9.0MB/s
Requirement already satisfied: IPython in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (5.5.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (3.2.2)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.4.3)
Collecting pyLDAvis
  Downloading https://files.pythonhosted.org/packages/a5/3a/af82e070a8a96e13217c8f362f9a73e82d61ac8fff3a2561946a97f96266/pyLDAvis-2.1.2.tar.gz (1.6MB)
     |████████████████████████████████| 1.6MB 55.4MB/s
Requirement already satisfied: nltk in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (3.2.5)
Requirement already satisfied: mlxtend in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.14.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (1.0.5)
Collecting kmodes>=0.10.1
  Downloading https://files.pythonhosted.org/packages/b2/55/d8ec1ae1f7e1e202a8a4184c6852a3ee993b202b0459672c699d0ac18fc8/kmodes-0.10.2-py2.py3-none-any.whl
Collecting datefinder>=0.7.0
  Downloading https://files.pythonhosted.org/packages/0c/4f/29524c9ca35d2ba1a8a3c6c895b90fc92525cf0fe357f747133890953ebe/datefinder-0.7.1-py2.py3-none-any.whl
Requirement already satisfied: umap-learn in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.4.6)
Requirement already satisfied: seaborn in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.10.1)
Collecting pandas-profiling>=2.3.0
  Downloading https://files.pythonhosted.org/packages/b9/94/ef8ef4517540d13406fcc0b8adfd75336e014242c69bd4162ab46931f36a/pandas_profiling-2.8.0-py2.py3-none-any.whl (259kB)
     |████████████████████████████████| 266kB 40.7MB/s
Requirement already satisfied: spacy in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (2.2.4)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (7.5.1)
Collecting mlflow
  Downloading https://files.pythonhosted.org/packages/00/2f/2529268d85af0a1521b0b7c137b63b731dff4784e1322fb3055403a959fb/mlflow-1.10.0-py3-none-any.whl (12.4MB)
     |████████████████████████████████| 12.4MB 54.5MB/s
Collecting catboost
  Downloading https://files.pythonhosted.org/packages/96/6c/6608210b29649267de52001b09e369777ee2a5cfe1c71fa75eba82a4f2dc/catboost-0.24-cp36-none-manylinux1_x86_64.whl (65.9MB)
     |████████████████████████████████| 65.9MB 59kB/s
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (1.18.5)
Requirement already satisfied: cufflinks>=0.17.0 in /usr/local/lib/python3.6/dist-packages (from pycaret==2.0) (0.17.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from lightgbm>=2.3.1->pycaret==2.0) (1.4.1)
Collecting zope.interface
  Downloading https://files.pythonhosted.org/packages/57/33/565274c28a11af60b7cfc0519d46bde4125fcd7d32ebc0a81b480d0e8da6/zope.interface-5.1.0-cp36-cp36m-manylinux2010_x86_64.whl (234kB)
     |████████████████████████████████| 235kB 56.0MB/s
Requirement already satisfied: pytz in /usr/local/lib/python3.6/dist-packages (from DateTime>=4.3->pycaret==2.0) (2018.9)
Collecting threadpoolctl>=2.0.0
  Downloading https://files.pythonhosted.org/packages/f7/12/ec3f2e203afa394a149911729357aa48affc59c20e2c1c8297a60f33f133/threadpoolctl-2.1.0-py3-none-any.whl
Requirement already satisfied: pillow in /usr/local/lib/python3.6/dist-packages (from wordcloud->pycaret==2.0) (7.0.0)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly>=4.4.1->pycaret==2.0) (1.3.3)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from plotly>=4.4.1->pycaret==2.0) (1.15.0)
Requirement already satisfied: smart-open>=1.2.1 in /usr/local/lib/python3.6/dist-packages (from gensim->pycaret==2.0) (2.1.0)
Requirement already satisfied: cycler>=0.10.0 in /usr/local/lib/python3.6/dist-packages (from yellowbrick>=1.0.1->pycaret==2.0) (0.10.0)
Collecting combo
  Downloading https://files.pythonhosted.org/packages/0a/2a/61b6ac584e75d8df16dc27962aa5fe99d76b09da5b6710e83d4862c84001/combo-0.1.1.tar.gz
Requirement already satisfied: numba>=0.35 in /usr/local/lib/python3.6/dist-packages (from pyod->pycaret==2.0) (0.48.0)
Collecting suod
  Downloading https://files.pythonhosted.org/packages/a1/87/9170cabe1b5e10a7d095c0e28f2e30e7c1886a13f063de85d3cfacc06f4b/suod-0.0.4.tar.gz (2.1MB)
     |████████████████████████████████| 2.1MB 47.3MB/s
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (49.2.0)
Requirement already satisfied: pygments in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (2.1.3)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (0.8.1)
Requirement already satisfied: pexpect; sys_platform != "win32" in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (4.8.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (1.0.18)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (4.3.3)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.6/dist-packages (from IPython->pycaret==2.0) (0.7.5)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->pycaret==2.0) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->pycaret==2.0) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->pycaret==2.0) (2.4.7)
Requirement already satisfied: wheel>=0.23.0 in /usr/local/lib/python3.6/dist-packages (from pyLDAvis->pycaret==2.0) (0.34.2)
Requirement already satisfied: jinja2>=2.7.2 in /usr/local/lib/python3.6/dist-packages (from pyLDAvis->pycaret==2.0) (2.11.2)
Requirement already satisfied: numexpr in /usr/local/lib/python3.6/dist-packages (from pyLDAvis->pycaret==2.0) (2.7.1)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages (from pyLDAvis->pycaret==2.0) (3.6.4)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pyLDAvis->pycaret==2.0) (0.16.0)
Collecting funcy
  Downloading https://files.pythonhosted.org/packages/ce/4b/6ffa76544e46614123de31574ad95758c421aae391a1764921b8a81e1eae/funcy-1.14.tar.gz (548kB)
     |████████████████████████████████| 552kB 47.8MB/s
Requirement already satisfied: regex>=2017.02.08 in /usr/local/lib/python3.6/dist-packages (from datefinder>=0.7.0->pycaret==2.0) (2019.12.20)
Collecting visions[type_image_path]==0.4.4
  Downloading https://files.pythonhosted.org/packages/4a/03/5a45d542257830cf1d9da2cdc1c0bc6f55a9212937b70fdd6d7031b46d6c/visions-0.4.4-py3-none-any.whl (59kB)
     |████████████████████████████████| 61kB 5.8MB/s
Collecting htmlmin>=0.1.12
  Downloading https://files.pythonhosted.org/packages/b3/e7/fcd59e12169de19f0131ff2812077f964c6b960e7c09804d30a7bf2ab461/htmlmin-0.1.12.tar.gz
Collecting confuse>=1.0.0
  Downloading https://files.pythonhosted.org/packages/b5/6d/bedc0d1068bd244cee05843313cbec6cebb9f01f925538269bababc6d887/confuse-1.3.0-py2.py3-none-any.whl (64kB)
     |████████████████████████████████| 71kB 6.9MB/s
Collecting tangled-up-in-unicode>=0.0.6
  Downloading https://files.pythonhosted.org/packages/4a/e2/e588ab9298d4989ce7fdb2b97d18aac878d99dbdc379a4476a09d9271b68/tangled_up_in_unicode-0.0.6-py3-none-any.whl (3.1MB)
     |████████████████████████████████| 3.1MB 46.4MB/s
Requirement already satisfied: missingno>=0.4.2 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling>=2.3.0->pycaret==2.0) (0.4.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling>=2.3.0->pycaret==2.0) (2.23.0)
Collecting tqdm>=4.43.0
  Downloading https://files.pythonhosted.org/packages/28/7e/281edb5bc3274dfb894d90f4dbacfceaca381c2435ec6187a2c6f329aed7/tqdm-4.48.2-py2.py3-none-any.whl (68kB)
     |████████████████████████████████| 71kB 7.1MB/s
Collecting phik>=0.9.10
  Downloading https://files.pythonhosted.org/packages/01/5a/7ef1c04ce62cd72f900c06298dc2385840550d5c653a0dbc19109a5477e6/phik-0.10.0-py3-none-any.whl (599kB)
     |████████████████████████████████| 604kB 36.1MB/s
Requirement already satisfied: astropy>=4.0 in /usr/local/lib/python3.6/dist-packages (from pandas-profiling>=2.3.0->pycaret==2.0) (4.0.1.post1)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (1.0.2)
Requirement already satisfied: wasabi<1.1.0,>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (0.7.1)
Requirement already satisfied: srsly<1.1.0,>=1.0.2 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (1.0.2)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (2.0.3)
Requirement already satisfied: plac<1.2.0,>=0.9.6 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (1.1.3)
Requirement already satisfied: blis<0.5.0,>=0.4.0 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (0.4.1)
Requirement already satisfied: thinc==7.4.0 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (7.4.0)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (3.0.2)
Requirement already satisfied: catalogue<1.1.0,>=0.0.7 in /usr/local/lib/python3.6/dist-packages (from spacy->pycaret==2.0) (1.0.0)
Requirement already satisfied: widgetsnbextension~=3.5.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets->pycaret==2.0) (3.5.1)
Requirement already satisfied: nbformat>=4.2.0 in /usr/local/lib/python3.6/dist-packages (from ipywidgets->pycaret==2.0) (5.0.7)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.6/dist-packages (from ipywidgets->pycaret==2.0) (4.10.1)
Requirement already satisfied: click>=7.0 in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (7.1.2)
Collecting gitpython>=2.1.0
  Downloading https://files.pythonhosted.org/packages/f9/1e/a45320cab182bf1c8656107b3d4c042e659742822fc6bff150d769a984dd/GitPython-3.1.7-py3-none-any.whl (158kB)
     |████████████████████████████████| 163kB 60.8MB/s
Collecting databricks-cli>=0.8.7
  Downloading https://files.pythonhosted.org/packages/1e/57/5c2d6b83cb8753d12f548e89f91037632baa8289677c1b2ab2adf14bf6b2/databricks-cli-0.11.0.tar.gz (49kB)
     |████████████████████████████████| 51kB 5.5MB/s
Collecting alembic
  Downloading https://files.pythonhosted.org/packages/60/1e/cabc75a189de0fbb2841d0975243e59bde8b7822bacbb95008ac6fe9ad47/alembic-1.4.2.tar.gz (1.1MB)
     |████████████████████████████████| 1.1MB 50.7MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: entrypoints in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (0.3)
Collecting sqlalchemy<=1.3.13
  Downloading https://files.pythonhosted.org/packages/af/47/35edeb0f86c0b44934c05d961c893e223ef27e79e1f53b5e6f14820ff553/SQLAlchemy-1.3.13.tar.gz (6.0MB)
     |████████████████████████████████| 6.0MB 51.3MB/s
Requirement already satisfied: Flask in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (1.1.2)
Collecting gunicorn; platform_system != "Windows"
  Downloading https://files.pythonhosted.org/packages/69/ca/926f7cd3a2014b16870086b2d0fdc84a9e49473c68a8dff8b57f7c156f43/gunicorn-20.0.4-py2.py3-none-any.whl (77kB)
     |████████████████████████████████| 81kB 6.8MB/s
Requirement already satisfied: protobuf>=3.6.0 in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (3.12.4)
Collecting docker>=4.0.0
  Downloading https://files.pythonhosted.org/packages/65/10/d18c41f2bd846c89c9030424a58be3d9752fac27780f8608284fa893feb4/docker-4.3.0-py2.py3-none-any.whl (145kB)
     |████████████████████████████████| 153kB 60.5MB/s
Requirement already satisfied: pyyaml in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (3.13)
Collecting prometheus-flask-exporter
  Downloading https://files.pythonhosted.org/packages/84/b0/7549899a75e7ef0be5f8969094d0709e5dcc51dc21d58cc86b8d69441dce/prometheus_flask_exporter-0.15.4.tar.gz
Collecting querystring-parser
  Downloading https://files.pythonhosted.org/packages/4a/fa/f54f5662e0eababf0c49e92fd94bf178888562c0e7b677c8941bbbcd1bd6/querystring_parser-1.2.4.tar.gz
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (1.3.0)
Collecting gorilla
  Downloading https://files.pythonhosted.org/packages/e3/56/5a683944cbfc77e429c6f03c636ca50504a785f60ffae91ddd7f5f7bb520/gorilla-0.3.0-py2.py3-none-any.whl
Requirement already satisfied: sqlparse in /usr/local/lib/python3.6/dist-packages (from mlflow->pycaret==2.0) (0.3.1)
Collecting azure-storage-blob>=12.0
  Downloading https://files.pythonhosted.org/packages/60/dc/3c25aeab827266c019e13abc07f31b5f47d93f1b8548a417c81c89c9d021/azure_storage_blob-12.4.0-py2.py3-none-any.whl (326kB)
     |████████████████████████████████| 327kB 53.5MB/s
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost->pycaret==2.0) (0.10.1)
Requirement already satisfied: colorlover>=0.2.1 in /usr/local/lib/python3.6/dist-packages (from cufflinks>=0.17.0->pycaret==2.0) (0.3.0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.6/dist-packages (from smart-open>=1.2.1->gensim->pycaret==2.0) (1.14.37)
Requirement already satisfied: boto in /usr/local/lib/python3.6/dist-packages (from smart-open>=1.2.1->gensim->pycaret==2.0) (2.49.0)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.35->pyod->pycaret==2.0) (0.31.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.6/dist-packages (from pexpect; sys_platform != "win32"->IPython->pycaret==2.0) (0.6.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.6/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->IPython->pycaret==2.0) (0.2.5)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.6/dist-packages (from traitlets>=4.2->IPython->pycaret==2.0) (0.2.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.6/dist-packages (from jinja2>=2.7.2->pyLDAvis->pycaret==2.0) (1.1.1)
Requirement already satisfied: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pyLDAvis->pycaret==2.0) (8.4.0)
Requirement already satisfied: atomicwrites>=1.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pyLDAvis->pycaret==2.0) (1.4.0)
Requirement already satisfied: pluggy<0.8,>=0.5 in /usr/local/lib/python3.6/dist-packages (from pytest->pyLDAvis->pycaret==2.0) (0.7.1)
Requirement already satisfied: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pyLDAvis->pycaret==2.0) (1.9.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest->pyLDAvis->pycaret==2.0) (19.3.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.6/dist-packages (from visions[type_image_path]==0.4.4->pandas-profiling>=2.3.0->pycaret==2.0) (2.4)
Collecting imagehash; extra == "type_image_path"
  Downloading https://files.pythonhosted.org/packages/1a/5d/cc81830be3c4705a46cdbca74439b67f1017881383ba0127c41c4cecb7b3/ImageHash-4.1.0.tar.gz (291kB)
     |████████████████████████████████| 296kB 31.7MB/s
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=2.23.0->pandas-profiling>=2.3.0->pycaret==2.0) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=2.23.0->pandas-profiling>=2.3.0->pycaret==2.0) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=2.23.0->pandas-profiling>=2.3.0->pycaret==2.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=2.23.0->pandas-profiling>=2.3.0->pycaret==2.0) (2020.6.20)
Requirement already satisfied: importlib-metadata>=0.20; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from catalogue<1.1.0,>=0.0.7->spacy->pycaret==2.0) (1.7.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.6/dist-packages (from widgetsnbextension~=3.5.0->ipywidgets->pycaret==2.0) (5.3.1)
Requirement already satisfied: jupyter-core in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret==2.0) (4.6.3)
Requirement already satisfied: jsonschema!=2.5.0,>=2.4 in /usr/local/lib/python3.6/dist-packages (from nbformat>=4.2.0->ipywidgets->pycaret==2.0) (2.6.0)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.0) (5.1.1)
Requirement already satisfied: jupyter-client in /usr/local/lib/python3.6/dist-packages (from ipykernel>=4.5.1->ipywidgets->pycaret==2.0) (5.3.5)
Collecting gitdb<5,>=4.0.1
  Downloading https://files.pythonhosted.org/packages/48/11/d1800bca0a3bae820b84b7d813ad1eff15a48a64caea9c823fc8c1b119e8/gitdb-4.0.5-py3-none-any.whl (63kB)
     |████████████████████████████████| 71kB 7.3MB/s

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import drive, files
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/gdrive

In [ ]:
# Load the data
obs_data_vis = np.load('/content/gdrive/My Drive/Colab Notebooks/Visobs.npy', allow_pickle=True)
model_data_vis = np.load('/content/gdrive/My Drive/Colab Notebooks/Vismodel.npy', allow_pickle=True)

obs_data_T = np.load('/content/gdrive/My Drive/Colab Notebooks/Tobs.npy', allow_pickle=True)
model_data_T = np.load('/content/gdrive/My Drive/Colab Notebooks/Tmodel.npy', allow_pickle=True)

obs_data_Td = np.load('/content/gdrive/My Drive/Colab Notebooks/Tdobs.npy', allow_pickle=True)
model_data_Td = np.load('/content/gdrive/My Drive/Colab Notebooks/Tdmodel.npy', allow_pickle=True)

In [ ]:
# Max model visibility data is 9999 so truncate model vis to that
model_data_vis[model_data_vis > np.max(obs_data_vis)] = np.max(obs_data_vis)

In [ ]:
# Bin the data
bins = [0, 150, 350, 600, 800, 1500, 3000, 5000, 10000]
obs_data_vis = pd.cut(obs_data_vis, bins, labels=[0,1,2,3,4,5,6,7])
model_binned = np.zeros(model_data_vis.shape)
for i in range(4):
  model_binned[i,:] = pd.cut(model_data_vis[i,:], bins, labels=[0,1,2,3,4,5,6,7])
model_data_vis = model_binned

In [ ]:
# Normalize the Td/T data
obs_data_T = (obs_data_T-np.mean(obs_data_T))/np.std(obs_data_T)
obs_data_Td = (obs_data_Td-np.mean(obs_data_Td))/np.std(obs_data_Td)

model_data_T = (model_data_T-np.mean(model_data_T))/np.std(model_data_T)
model_data_Td = (model_data_Td-np.mean(model_data_Td))/np.std(model_data_Td)

In [ ]:
# Use the past_history nr of data to predict future_target nr of data
past_history = 6
future_target = 3

In [ ]:
# Add obs data to model data
dataset = np.concatenate((model_data_vis, np.reshape(obs_data_vis,(1,-1))), axis=0)
dataset_vis = np.swapaxes(dataset,0,1)

dataset = np.concatenate((model_data_T, np.reshape(obs_data_T,(1,-1))), axis=0)
dataset_T = np.swapaxes(dataset,0,1)

dataset = np.concatenate((model_data_Td, np.reshape(obs_data_Td,(1,-1))), axis=0)
dataset_Td = np.swapaxes(dataset,0,1)

dataset_vis.shape

(27001, 5)

In [ ]:
def multivariate_data(dataset, target, start_index, end_index, history_size,
                      target_size, step, single_step=False):
  data = []
  labels = []

  start_index = start_index + history_size
  if end_index is None:
    end_index = len(dataset) - target_size

  for i in range(start_index, end_index):
    #indices = range(i-history_size, i, step)
    indices = range(i-history_size, i+target_size, step)
    data.append(dataset[indices])

    if single_step:
      labels.append(target[i+target_size])
    else:
      labels.append(target[i:i+target_size])

  return np.array(data), np.array(labels)

In [ ]:
STEP = 1

# This is the visibility (target) dataset
x_train_vis, y_train_vis = multivariate_data(dataset_vis, dataset_vis[:,4], 0,
                                                 None, past_history,
                                                 future_target, STEP)
# These are the auxiliary (T, Td) datasets
x_train_T, _ = multivariate_data(dataset_T, dataset_T[:,4], 0,
                                                 None, past_history,
                                                 future_target, STEP)

x_train_Td, _ = multivariate_data(dataset_Td, dataset_Td[:,4], 0,
                                                 None, past_history,
                                                 future_target, STEP)

In [ ]:
# Using T-Td as feature
x_train_TTd = x_train_T-x_train_Td

In [ ]:
# Keep only 10% of cases where there has been a constant (max) visibility
idx = np.sum(y_train_vis, axis=1) != np.max(np.sum(y_train_vis, axis=1))
idx_2 = np.sum(y_train_vis, axis=1) == np.max(np.sum(y_train_vis, axis=1))

x_train_vis_1 = x_train_vis[idx,];  x_train_vis_2 = x_train_vis[idx_2,]
n_c = np.int(0.1*len(x_train_vis_2))

y_train_vis_1 = y_train_vis[idx,]; y_train_vis_2 = y_train_vis[idx_2,]
x_train_TTd_1 = x_train_TTd[idx,]; x_train_TTd_2 = x_train_TTd[idx_2,]
x_train_T_1 = x_train_T[idx,]; x_train_T_2 = x_train_T[idx_2,]

x_train_vis = np.concatenate((x_train_vis_1, x_train_vis_2[:n_c]))
x_train_TTd = np.concatenate((x_train_TTd_1, x_train_TTd_2[:n_c]))
x_train_T = np.concatenate((x_train_T_1, x_train_T_2[:n_c]))
y_train_vis = np.concatenate((y_train_vis_1, y_train_vis_2[:n_c]))

In [ ]:
# Set the future obs to the average of the model data
x_train_vis[:,past_history:,4] = np.round(np.average(x_train_vis[:,past_history:,0:4], axis=2))
x_train_T[:,past_history:,4] = np.round(np.average(x_train_T[:,past_history:,0:4], axis=2))
x_train_Td[:,past_history:,4] = np.round(np.average(x_train_Td[:,past_history:,0:4], axis=2))

In [ ]:
# check version
from pycaret.utils import version
version()

2.0

In [ ]:
print(y_train_vis.shape)

(4879, 3)

In [ ]:
keys_y = ['y_vis']
keys_vis_obs_x = ['x_vis_obs_step_' + str(k) for k in range(past_history+future_target)]
keys_vis_model_x = ['x_vis_model_step_' + str(k) for k in range(past_history+future_target)]
keys_T_obs_x = ['x_T_obs_step_' + str(k) for k in range(past_history+future_target)]
keys_T_model_x = ['x_T_model_step_' + str(k) for k in range(past_history+future_target)]
keys_TTd_obs_x = ['x_TTd_obs_step_' + str(k) for k in range(past_history+future_target)]
keys_TTd_model_x = ['x_TTd_model_step_' + str(k) for k in range(past_history+future_target)]
keys = keys_y + keys_vis_obs_x + keys_vis_model_x + keys_T_obs_x + \
       keys_T_model_x + keys_TTd_obs_x + keys_TTd_model_x

In [ ]:
# Change in y_train_vis the second index to 0, 1, 2, ..., future_step-1
vals = np.concatenate((np.expand_dims(y_train_vis[:,0],1), x_train_vis[:,:,4], 
                       x_train_vis[:,:,0:4].mean(axis=2), 
                       x_train_T[:,:,4],
                       x_train_T[:,:,0:4].mean(axis=2),
                       x_train_TTd[:,:,4],
                       x_train_TTd[:,:,0:4].mean(axis=2)), axis = 1)

In [ ]:
data = {}
j = 0
for i in keys:
  data[i] = pd.Series(vals[:,j])
  j += 1
data = pd.DataFrame(data)

In [ ]:
data = data[data.y_vis != 0]

In [ ]:
from pycaret.classification import *
clf = setup(data, target='y_vis', session_id=123, log_experiment=True, train_size=0.9,
            experiment_name='step_0')

IntProgress(value=0, description='Processing: ', max=13)

Initiated  . . . . . . . . . . . . . . . . . .                     18:17:25
Status     . . . . . . . . . . . . . . . . . .  Preparing Data for Modeling
ETC        . . . . . . . . . . . . . . . . . .              Calculating ETC

Text(value="Following data types have been inferred automatically, if they are correct press enter to continue…

                   Data Type
y_vis                  Label
x_vis_obs_step_0     Numeric
x_vis_obs_step_1     Numeric
x_vis_obs_step_2     Numeric
x_vis_obs_step_3     Numeric
x_vis_obs_step_4     Numeric
x_vis_obs_step_5     Numeric
x_vis_obs_step_6     Numeric
x_vis_obs_step_7     Numeric
x_vis_obs_step_8     Numeric
x_vis_model_step_0   Numeric
x_vis_model_step_1   Numeric
x_vis_model_step_2   Numeric
x_vis_model_step_3   Numeric
x_vis_model_step_4   Numeric
x_vis_model_step_5   Numeric
x_vis_model_step_6   Numeric
x_vis_model_step_7   Numeric
x_vis_model_step_8   Numeric
x_T_obs_step_0       Numeric
x_T_obs_step_1       Numeric
x_T_obs_step_2       Numeric
x_T_obs_step_3       Numeric
x_T_obs_step_4       Numeric
x_T_obs_step_5       Numeric
x_T_obs_step_6       Numeric
x_T_obs_step_7       Numeric
x_T_obs_step_8       Numeric
x_T_model_step_0     Numeric
x_T_model_step_1     Numeric
x_T_model_step_2     Numeric
x_T_model_step_3     Numeric
x_T_model_step_4     Numeric
x_T_model_step_5     Numeric
x_T_model_step_6     Numeric
x_T_model_step_7     Numeric
x_T_model_step_8     Numeric
x_TTd_obs_step_0     Numeric
x_TTd_obs_step_1     Numeric
x_TTd_obs_step_2     Numeric
x_TTd_obs_step_3     Numeric
x_TTd_obs_step_4     Numeric
x_TTd_obs_step_5     Numeric
x_TTd_obs_step_6     Numeric
x_TTd_obs_step_7     Numeric
x_TTd_obs_step_8     Numeric
x_TTd_model_step_0   Numeric
x_TTd_model_step_1   Numeric
x_TTd_model_step_2   Numeric
x_TTd_model_step_3   Numeric
x_TTd_model_step_4   Numeric
x_TTd_model_step_5   Numeric
x_TTd_model_step_6   Numeric
x_TTd_model_step_7   Numeric
x_TTd_model_step_8   Numeric

In [ ]:
best_model = compare_models(blacklist = ['catboost'])

In [ ]:
xgb = create_model('xgboost')

In [ ]:
# # Create ensemble models
# bagged_xgb = ensemble_model(xgb)

In [ ]:
# Plot model
plot_model(xgb)

In [ ]:
# # Predict model
# predictions = predict_model(xgb)

In [ ]:
# Predict model
predictions = predict_model(xgb)

In [ ]:
# AutoML
# best = automl(optimize='Accuracy')